### ISSUE TITLE
Any chance for opentrack support?

### ISSUE THREAD

**Issue by damnvaman** [Eugene-E0a80fd8080ff8e/HeadTracker6DoF#1]
Have you looked into opentrack support for IR led clips (no shaky or stability issues, free version of TrackIR)

**Comment by Eugene-E0a80fd8080ff8e** [comment]
Why not? I will look into this.
I can see opentrack also supports webcam headtracking [https://www.youtube.com/watch?v=LPlahUVPx4o](https://www.youtube.com/watch?v=LPlahUVPx4o) .
Have you used it? Can you share your experience ?

**Comment by Eugene-E0a80fd8080ff8e** [comment]
- support for opentrack has been added in version v0.3
To use this, run opentrack with its output set to "UDP over network" with ip 127.0.0.1 and port 62731
(this is for the case if you run opentrack on the same computer as VaM).
